React rework
404busters/oshk-kaidemo pull request #1
Opened 2017-01-23 22:22 UTC by railsstudent

2017-01-24 05:46 UTC, tonyhhyip commented
Please upload some screen capture if possible

2017-01-24 15:04 UTC, railsstudent commented
Fixing it based on feedback

2017-01-24 15:15 UTC, tonyhhyip commented
@railsstudent Do you forget to git push?

2017-01-24 15:58 UTC, railsstudent commented
![screen shot 2017-01-24 at 6 18 36 am](https://cloud.githubusercontent.com/assets/1159649/22254949/f38a00d0-e290-11e6-84af-c5e1b3502339.png)
![screen shot 2017-01-24 at 11 55 06 pm](https://cloud.githubusercontent.com/assets/1159649/22254956/f6395f60-e290-11e6-910a-7b1702022ad0.png)

2017-01-24 15:59 UTC, railsstudent commented
![screen shot 2017-01-24 at 11 54 57 pm](https://cloud.githubusercontent.com/assets/1159649/22255041/1ecf4a52-e291-11e6-88af-93f5cc30e150.png)

2017-01-24 18:48 UTC, tonyhhyip requested changes
Great Job, just some minor issue and some way to be improved. Please take a look at the lines I comment on and consider to fix it

2017-01-24 18:48 UTC, tonyhhyip commented on .yarnclean
> +
Please remove this file with `git rm --cached .yarnclean`

2017-01-24 18:48 UTC, tonyhhyip commented on assets/js/InputCharacterComponent.jsx
> +        <div style={styles.bigfontStyle}>
Font family of freehkfonts is missed

2017-01-24 18:48 UTC, tonyhhyip commented on package.json
> +  "babel": {
You may remove the part as you have the .babelrc

2017-01-24 18:48 UTC, tonyhhyip commented on public/index.html
> +    <!--script src="/js/app.js" type="text/javascript"></script -->
Please remove commented lines

2017-01-24 18:48 UTC, tonyhhyip commented on assets/js/CreditComponent.jsx
> +  constructor(props) {
Remove this do nothing constructor

2017-01-24 22:46 UTC, railsstudent commented on .yarnclean
> +
Done

2017-01-24 22:46 UTC, railsstudent commented on assets/js/InputCharacterComponent.jsx
> +        <div style={styles.bigfontStyle}>
Done

2017-01-24 22:46 UTC, railsstudent commented on package.json
> +  "babel": {
Done

2017-01-24 22:46 UTC, railsstudent commented on public/index.html
> +    <!--script src="/js/app.js" type="text/javascript"></script -->
Done

2017-01-24 22:47 UTC, railsstudent commented on assets/js/CreditComponent.jsx
> +  constructor(props) {
Done

2017-01-24 22:47 UTC, railsstudent commented
Please review the changes again.

2017-01-25 01:42 UTC, tonyhhyip approved these changes

2017-01-25 01:43 UTC, tonyhhyip commented
Some place can improve like code style, I will handle it

2017-01-25 01:43 UTC, merged

2017-01-25 04:59 UTC, railsstudent commented
Sure, thanks.